stages:
  create_pipeline:
    cmd: python diabetes-predict/create_features_and_base_pipeline.py
    deps:
      - pipeline.cfg  # Archivo de configuración
      - diabetes-predict/create_features_and_base_pipeline.py
    outs:
      - artifacts/pipeline.pkl  # Output generado por tu script

  configure_and_fit:
    cmd: python diabetes-predict/configure_and_fit_pipeline.py
    deps:
      - artifacts/pipeline.pkl  # Entrada generada por la etapa anterior
      - data/raw/diabetes.csv  # Dataset usado en esta etapa
      - diabetes-predict/configure_and_fit_pipeline.py
    outs:
      - artifacts/trainded_pipeline.pkl  # Pipeline entrenado con el modelo

  predict:
    cmd: python diabetes-predict/predict_pipeline.py
    deps:
      - artifacts/trainded_pipeline.pkl  # Entrada del pipeline entrenado
      - diabetes-predict/predict_pipeline.py
      - data/raw/diabetes.csv  # Datos sobre los cuales se harán predicciones
    outs:
      - data/predictions/predictions.csv  # Archivo de predicciones generado